name: Update Version Matrix

on:
  workflow_dispatch:

  schedule:
    - cron: '0 17 * * 0'

jobs:
  run_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Fetch all backup-utils release versions
        run: gh api --paginate /repos/github/backup-utils/releases -q '.[].tag_name' | sort -rV > bvs.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch all GitHub Enterprise Server release versions
        run: |
          curl -s https://raw.githubusercontent.com/kyanny/github-enterprise-releases.json/main/releases.json | jq -r '.[].title' | sort -V | perl -nle 'BEGIN{ $, = "\n"; @not_eleven = () };
            /^11\./ ? print : push @not_eleven, $_;
            END{ print @not_eleven }' | tac > gvs.txt
      - name: Update matrix and README
        run: bundle exec ruby main.rb
      - name: Update Google Sheet
        run: curl -s https://script.google.com/macros/s/AKfycbweKZloTv9KOprf7QoHOKOv9el2LZqTjNXmB_fUZupqoCIsmHc4s1diB3yk5aiW8YfA/exec
      - uses: stefanzweifel/git-auto-commit-action@v4
