name: Update Version Matrix

on:
  workflow_dispatch:

  schedule:
    # At 17:00 on Sunday.
    # Because GAS trigger runs 00:00 ~ 01:00 every Monday (15:00 ~ 16:00 every Sunday)
    - cron: '0 17 * * 0'

jobs:
  run_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: main.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
